version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python WebApp/manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1