# Generated by Django 3.0.3 on 2020-07-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200625_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtfsstop',
            name='plate_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
