# Generated by Django 3.0.3 on 2020-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('stopid', models.IntegerField(primary_key=True, serialize=False)),
                ('displaystopid', models.IntegerField(blank=True, null=True)),
                ('shortname', models.CharField(blank=True, max_length=200, null=True)),
                ('shortnamelocalized', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lastupdated', models.DateField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('op_type', models.IntegerField(blank=True, null=True)),
                ('routes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_bus_stops',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StopSequence',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('shape_id', models.CharField(max_length=30)),
                ('operator', models.CharField(max_length=50)),
                ('stop_sequence', models.IntegerField()),
                ('route_name', models.CharField(max_length=10)),
                ('direction_inbound', models.BooleanField()),
                ('plate_code', models.IntegerField(blank=True, null=True)),
                ('short_common_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('short_common_name_ga', models.CharField(blank=True, max_length=100, null=True)),
                ('has_pole', models.BooleanField(blank=True, null=True)),
                ('has_shelter', models.BooleanField(blank=True, null=True)),
                ('carousel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('flag_data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'stopsequences',
                'managed': True,
                'unique_together': {('shape_id', 'stop_sequence')},
            },
        ),
        migrations.CreateModel(
            name='RouteShape',
            fields=[
                ('unique_point_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('shape_id', models.CharField(max_length=30)),
                ('shape_pt_lat', models.FloatField(blank=True, null=True)),
                ('shape_pt_lon', models.FloatField(blank=True, null=True)),
                ('shape_pt_sequence', models.IntegerField()),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routeshapes',
                'managed': True,
                'unique_together': {('shape_id', 'shape_pt_sequence')},
            },
        ),
    ]
