# Generated by Django 3.0.3 on 2020-06-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteShape',
        ),
        migrations.DeleteModel(
            name='StopSequence',
        ),
        migrations.AlterModelOptions(
            name='busstop',
            options={},
        ),
    ]
