# Generated by Django 3.0.3 on 2020-06-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gtfscalendar_calendar_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtfscalendar',
            old_name='calendar_name',
            new_name='display_days',
        ),
    ]
