# Generated by Django 3.0.3 on 2020-06-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200615_1519'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='busstop',
            table='bus_stops',
        ),
    ]
