# Generated by Django 3.0.3 on 2020-06-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200615_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTFSRoute',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gtfs_routes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GTFSStopTime',
            fields=[
                ('unique_trip_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('trip_id', models.CharField(max_length=50)),
                ('arrival_time', models.DateField(blank=True, null=True)),
                ('departure_time', models.DateField(blank=True, null=True)),
                ('stop_id', models.CharField(max_length=50)),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'gtfs_stop_times',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GTFSTrip',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=20)),
                ('trip_id', models.CharField(max_length=70)),
                ('shape_id', models.CharField(max_length=30)),
                ('trip_headsign', models.CharField(max_length=200)),
                ('direction_id', models.IntegerField()),
            ],
            options={
                'db_table': 'gtfs_trips',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='busstop',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='displaystopid',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='op_type',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='shortname',
        ),
        migrations.CreateModel(
            name='GTFSShape',
            fields=[
                ('unique_point_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('shape_id', models.CharField(max_length=30)),
                ('shape_pt_lat', models.FloatField(blank=True, null=True)),
                ('shape_pt_lon', models.FloatField(blank=True, null=True)),
                ('shape_pt_sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'shapes',
                'managed': True,
                'unique_together': {('shape_id', 'shape_pt_sequence')},
            },
        ),
    ]
