# Generated by Django 3.0.3 on 2020-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200615_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfsshape',
            name='unique_point_id',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='gtfsshape',
            table='gtfs_shapes',
        ),
    ]
