# Generated by Django 3.0.3 on 2020-07-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('api', '0004_gtfsstop_plate_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('file_name', models.CharField(max_length=128)),
                ('level_name', models.CharField(max_length=128)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'backend_log',
                'managed': True,
            },
        ),
    ]
