# Generated by Django 3.0.3 on 2020-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gtfsstop_plate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartdublinbusstop',
            name='localname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
