# Generated by Django 3.0.7 on 2020-07-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gtfsstop_plate_code 2'),
        ('api', '0005_smartdublinbusstop_localname 2'),
        ('api', '0005_smartdublinbusstop_localname'),
    ]

    operations = [
    ]
