# Generated by Django 3.0.3 on 2020-06-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200615_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfsstoptime',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtfsstoptime',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
