# Generated by Django 3.0.3 on 2020-07-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_backendlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendlog',
            name='file_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='backendlog',
            name='level_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='backendlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
