# Generated by Django 3.0.3 on 2020-06-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200615_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfsstoptime',
            name='arrival_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gtfsstoptime',
            name='departure_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
