# Generated by Django 3.0.3 on 2020-07-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200721_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendlog',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
