# Generated by Django 3.0.3 on 2020-08-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20200721_1109 2'),
        ('api', '0005_smartdublinbusstop_localname 3'),
        ('api', '0006_merge_20200721_1109'),
        ('api', '0004_gtfsstop_plate_code 3'),
    ]

    operations = [
    ]
