# Generated by Django 3.0.3 on 2020-06-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gtfsmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GTFSManager',
        ),
    ]
