# Generated by Django 3.0.3 on 2020-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='id',
        ),
        migrations.AddField(
            model_name='busstop',
            name='displaystopid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='fullnamelocalized',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='lastupdated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='op_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='operator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='shortname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='shortnamelocalized',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='stopid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
