# Generated by Django 3.0.3 on 2020-06-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0002_stopsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopsequence',
            name='carousel_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stopsequence',
            name='flag_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stopsequence',
            name='has_pole',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stopsequence',
            name='has_shelter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stopsequence',
            name='plate_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stopsequence',
            name='short_common_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stopsequence',
            name='short_common_name_ga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
