# Generated by Django 3.0.3 on 2020-06-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0002_auto_20200609_1626'),
    ]

    operations = [
    ]
