# Generated by Django 3.0.3 on 2020-06-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0003_auto_20200609_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
