# Generated by Django 3.0.3 on 2020-06-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0004_auto_20200609_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='fullnamelocalized',
        ),
    ]
