# Generated by Django 3.0.3 on 2020-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0005_remove_busstop_fullnamelocalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteShape',
            fields=[
                ('shape_id', models.CharField(max_length=30)),
                ('shape_pt_lat', models.FloatField(blank=True, null=True)),
                ('shape_pt_lon', models.FloatField(blank=True, null=True)),
                ('shape_pt_sequence', models.IntegerField(primary_key=True, serialize=False)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routeshapes',
                'managed': True,
                'unique_together': {('shape_id', 'shape_pt_sequence')},
            },
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
