version: "3.3"

services:
  web:
    build: .
    command: gunicorn dublin_bus.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  static_volume:
